# Generated by Django 4.2.9 on 2024-04-14 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10)),
                ('connection_sent_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('connection_sent_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connection_sent_by', to=settings.AUTH_USER_MODEL)),
                ('connection_sent_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connection_sent_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
